# Copyright (C) 2021. Huawei Technologies Co., Ltd. All rights reserved.
# This program is free software; you can redistribute it and/or modify
# it under the terms of the MIT License.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# MIT License for more details.

defaults:
  - training: likelihood_training
  - dataset: snips_75
  - lm: lstm
  - background_lm: lstm
  - embedder: glove_embedder

training.max_epochs: 100
training.optimizer.lr: 1e-4
training.back_optimizer.lr: 1e-4
background_lm.hidden_size: 256
background_lm.dropout: 0.0
background_lm.l2_coeff: 1e-4
lm.dropout: 0.3
lm.hidden_size: 512
training.train_batch_size: 64
training.early_stop.patience: 4
training.num_workers: 8

model_name: llr
device: 0
p_noise: 0.5
noise_type: 'uniform'
add_valid_to_vocab: false
add_test_to_vocab: false
experiment_name: 'debug'